name: Docker Image Base

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Set executable permissions
        run: chmod +x ./release.sh
      - name: Execute publishing script
        run: ./release.sh
        shell: bash
